/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/nutrition/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get daily intake
         * @description Fetch the user's aggregated daily macros and logged meals for today.
         */
        get: operations["get-daily-intake"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get historical aggregated intake
         * @description Fetch the user's aggregated macros over the past X days.
         */
        get: operations["get-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log scanned food
         * @description Log a previously scanned food item to the database
         */
        post: operations["log-food"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/log/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete meal log
         * @description Permanently removes a meal and its scanned ingredients from the user's diary.
         */
        delete: operations["delete-log"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan food image for nutritional information
         * @description Upload a base64-encoded food image and optionally provide a description. Returns detected food name and macro breakdown.
         */
        post: operations["scan-food"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/barcode/{barcode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up product by barcode
         * @description Look up a food product by its EAN/UPC barcode. First checks the local cache, then queries Open Food Facts, FSVO, and USDA FoodData Central.
         */
        get: operations["lookup-product-barcode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search products
         * @description Full-text search across cached and external food product databases. Results are deduplicated and cached for future queries.
         */
        get: operations["search-products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DailyIntakeOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/DailyIntakeOutputBody.json
             */
            readonly $schema?: string;
            /** @description Aggregated nutritional macro information */
            macros: components["schemas"]["MacroData"];
            /** @description List of meals logged today */
            meals: components["schemas"]["Meal"][] | null;
        };
        DailySummary: {
            /**
             * @description Date of the summary (YYYY-MM-DD)
             * @example 2024-10-24
             */
            date: string;
            /** @description Aggregated nutritional macro information for the day */
            macros: components["schemas"]["MacroData"];
        };
        DeleteLogOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/DeleteLogOutputBody.json
             */
            readonly $schema?: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        HistoryOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/HistoryOutputBody.json
             */
            readonly $schema?: string;
            /** @description Average daily macros over the period */
            averages: components["schemas"]["MacroData"];
            /** @description List of daily summaries */
            days: components["schemas"]["DailySummary"][] | null;
        };
        IngredientBody: {
            /** @description Nutritional macro information for this ingredient */
            macros: components["schemas"]["MacroData"];
            /**
             * @description Ingredient name
             * @example Grilled Chicken Breast
             */
            name: string;
            /**
             * Format: double
             * @description Quantity of the serving
             * @example 1.5
             */
            serving_quantity?: number;
            /**
             * Format: int64
             * @description Raw serving size generic value
             * @example 150
             */
            serving_size?: number;
            /**
             * @description Unit of the serving size (e.g., g, ml)
             * @example g
             */
            serving_unit?: string;
        };
        LogFoodInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/LogFoodInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: double
             * @description Detection confidence score (omit for product-based logs)
             * @example 0.92
             */
            confidence?: number;
            /**
             * @description Detected food name
             * @example Grilled Chicken Salad
             */
            food_name: string;
            /** @description Breakdown of individual ingredients with their macros (optional for product-based logs) */
            ingredients?: components["schemas"]["IngredientBody"][] | null;
            /** @description Nutritional macro information */
            macros: components["schemas"]["MacroData"];
            /**
             * @description Optional product reference ID
             * @example off-7613035466432
             */
            product_id?: string;
            /** @description Optional UUID of the user logging the meal (defaults to auth context if implemented) */
            user_id?: string;
        };
        LogFoodOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/LogFoodOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Database ID of the created food log
             * @example 1
             */
            id?: string;
            /**
             * @description Indicates whether the log was successfully saved
             * @example true
             */
            success: boolean;
        };
        MacroData: {
            /**
             * Format: int64
             * @description Total calories
             * @example 450
             */
            calories: number;
            /**
             * Format: double
             * @description Carbohydrates in grams
             * @example 45
             */
            carbs: number;
            /**
             * Format: double
             * @description Fat in grams
             * @example 15.5
             */
            fat: number;
            /**
             * Format: double
             * @description Fiber in grams
             * @example 5
             */
            fiber: number;
            /**
             * Format: double
             * @description Protein in grams
             * @example 25.5
             */
            protein: number;
        };
        MacrosOutput: {
            /**
             * Format: double
             * @description Calories per 100g
             * @example 56
             */
            calories: number;
            /**
             * Format: double
             * @description Carbohydrates per 100g (grams)
             * @example 5.1
             */
            carbs: number;
            /**
             * Format: double
             * @description Fat per 100g (grams)
             * @example 1.8
             */
            fat: number;
            /**
             * Format: double
             * @description Fiber per 100g (grams)
             * @example 0
             */
            fiber: number;
            /**
             * Format: double
             * @description Protein per 100g (grams)
             * @example 3.2
             */
            protein: number;
        };
        Meal: {
            /**
             * Format: int64
             * @description Total calories in the meal
             * @example 450
             */
            calories: number;
            /**
             * Format: double
             * @description AI Identification confidence score
             * @example 0.95
             */
            confidence: number;
            /**
             * @description Visual representation emoji
             * @example 🥗
             */
            emoji: string;
            /**
             * @description Database ID of the meal
             * @example 1
             */
            id: string;
            /** @description List of ingredients attached to this meal */
            ingredients?: components["schemas"]["IngredientBody"][] | null;
            /** @description Nutritional macro information for the meal */
            macros: components["schemas"]["MacroData"];
            /**
             * @description Food name
             * @example Grilled Chicken Salad
             */
            name: string;
            /**
             * @description Total estimated weight or serving size
             * @example 150g
             */
            serving_size: string;
            /**
             * @description Optional descriptive tag
             * @example High Protein
             */
            tag?: string;
            /**
             * @description Formatted local time of log
             * @example 08:15 AM
             */
            time: string;
        };
        ProductOutput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ProductOutput.json
             */
            readonly $schema?: string;
            /** @description EAN/UPC barcode */
            barcode: string;
            /** @description Brand name */
            brand: string;
            /** @description Product categories */
            categories: string[] | null;
            /** @description Composite product identifier */
            id: string;
            /** @description Product image URL */
            image_url: string;
            /** @description Nutritional values per 100g */
            macros: components["schemas"]["MacrosOutput"];
            /** @description Product display name */
            name: string;
            /** @description NutriScore grade (A-E) */
            nutri_score: string;
            /**
             * Format: double
             * @description Serving quantity in grams/ml
             */
            serving_quantity?: number;
            /** @description Human-readable serving size (e.g. 250ml) */
            serving_size?: string;
            /** @description Data source identifier */
            source: string;
        };
        ScanInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ScanInputBody.json
             */
            readonly $schema?: string;
            /** @description Optional meal description for better AI analysis */
            description?: string;
            /** @description Base64 encoded image data */
            image_base64: string;
        };
        ScanOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ScanOutputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: double
             * @description Detection confidence score
             * @example 0.92
             */
            confidence: number;
            /**
             * @description Detected food name
             * @example Grilled Chicken Salad
             */
            food_name: string;
            /** @description Breakdown of individual ingredients with their macros */
            ingredients: components["schemas"]["IngredientBody"][] | null;
            /** @description Nutritional macro information */
            macros: components["schemas"]["MacroData"];
            /**
             * @description Estimated serving size
             * @example 1 plate (350g)
             */
            serving_size: string;
        };
        SearchProductsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/SearchProductsOutputBody.json
             */
            readonly $schema?: string;
            /** @description Data attribution notice */
            attribution?: string;
            /** @description List of matching products */
            products: components["schemas"]["ProductOutput"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-daily-intake": {
        parameters: {
            query?: {
                /** @description Timezone offset in minutes (UTC - Local Time) */
                tz_offset?: number;
                /** @description Optional past date to fetch logs for (YYYY-MM-DD) */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyIntakeOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-history": {
        parameters: {
            query?: {
                /** @description Number of days to fetch history for */
                days?: number;
                /** @description Timezone offset in minutes (UTC - Local Time) */
                tz_offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "log-food": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogFoodInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogFoodOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-log": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the logged meal to delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteLogOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "scan-food": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ScanInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "lookup-product-barcode": {
        parameters: {
            query?: {
                /**
                 * @description Preferred language code (e.g. de, fr, en)
                 * @example de
                 */
                lang?: string;
            };
            header?: never;
            path: {
                /**
                 * @description EAN/UPC barcode to look up
                 * @example 7613035466432
                 */
                barcode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "search-products": {
        parameters: {
            query?: {
                /**
                 * @description Free-text search query
                 * @example nutella
                 */
                query?: string;
                /** @description Maximum number of results */
                limit?: number;
                /**
                 * @description Preferred language code (e.g. de, fr, en)
                 * @example de
                 */
                lang?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchProductsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
