-- Create a table for public profiles
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    weight NUMERIC(5,2),
    height NUMERIC(5,2),
    age INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Function to handle new user signups
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id)
    VALUES (new.id);
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to automatically create a profile for new users
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Create a table for food logs
CREATE TABLE food_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    food_name TEXT NOT NULL,
    detection_confidence NUMERIC(3,2) NOT NULL,
    calories INT NOT NULL,
    protein NUMERIC(6,2) NOT NULL,
    carbs NUMERIC(6,2) NOT NULL,
    fat NUMERIC(6,2) NOT NULL,
    fiber NUMERIC(6,2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX food_logs_user_id_idx ON food_logs (user_id);

-- Create food_log_ingredients table
CREATE TABLE food_log_ingredients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    food_log_id BIGINT NOT NULL REFERENCES food_logs(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    serving_size INT,
    serving_quantity NUMERIC(6,2),
    serving_unit TEXT,
    calories INT NOT NULL,
    protein NUMERIC(8, 2) NOT NULL,
    carbs NUMERIC(8, 2) NOT NULL,
    fat NUMERIC(8, 2) NOT NULL,
    fiber NUMERIC(8, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX food_log_ingredients_food_log_id_idx ON food_log_ingredients (food_log_id);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE food_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE food_log_ingredients ENABLE ROW LEVEL SECURITY;

-- For now, allow all access (since auth is for future)
CREATE POLICY "Enable all for profiles" ON public.profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for food_logs" ON food_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for food_log_ingredients" ON food_log_ingredients FOR ALL USING (true) WITH CHECK (true);
